# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 木夕木火のBlog
subtitle: 路漫漫其修远兮，吾将上下而求索
description: 理想主义者
keywords: 
author: 木夕木火
language: zh-cn
timezone:

# URL
## If your site is put in a subdirectory, set url as 'https://yoursite.com/child' and root as '/child/'
#url: https://www.wmjtxt.net
url: https://wmjtxt.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: flase # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace:
prism_plugin:
    mode: 'preprocess'
    theme: 'tomorrow'
    line_number: false
    custom_css:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 12
  order_by: 
    top: -1
    date: -1
  
# Category & Tag
default_category: uncategorized
category_map:
 tag_map: "相册"

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## https://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: hexo-theme-matery
theme: yilia
#theme: indigo
#theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/
#deployment.html
deploy:
  type: git
  repo: 
    github: git@github.com:wmjtxt/wmjtxt.github.io.git
    # coding: 你的coding仓库地址
  branch: master

backup:
  type: git
  message: backup my blog of https://wmjtxt.github.io/
  repository:
    # 你的github仓库地址，备份分支名（建议新建backup分支）
      github: https://github.com/wmjtxt/wmjtxt.github.io.git,backup
      # coding : https://git.coding.net/hojun/hojun.git,backup


douban:
    user: 175696698
    builtin: false
    book:
        title: 'This is my book title'
        quote: 'This is my book quote'
    movie:
        title: 'This is my movie title'
        quote: 'This is my movie quote'
    timeout: 10000

jsonContent:
    meta: false
    pages: false
    posts:
      title: true
      date: true
      path: true
      text: false
      raw: false
      content: false
      slug: false
      updated: false
      comments: false
      link: false
      permalink: false
      excerpt: false
      categories: false
      tags: true
      top: true

display-updated: true

search:
    path: search.xml
    field: post

postInfo:
    date: true
    update: true
    wordCount: true     #文章字数统计
    totalCount: true    #设置站点文章总字数统计为true
    min2read: true      #阅读时长
    readCount: true     #阅读次数

lazyload:
    enable: true
    onlypost: false
    loadingImg:

